### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by georgeAccnt-GH** [jacobgil/keras-cam#9]
Hi Jacob,

Can you please let me what license do you have for your code. I used some bits of your code to build CAM visualizations in a project that will be made public soon, and I need to make sure our code gets the right credit.

Thank you.
George

**Comment by jacobgil** [comment]
The license is that you can freely use this for anything you want :-)
Can be nice if you give a reference to this project, but that's up to you.

**Comment by georgeAccnt-GH** [comment]
Sounds good. Thank you.
George
